---
include:
  default:
    - profile::application::openssl::catrust

cinder::backends::enabled_backends:
  - lvm

profile::openstack::volume::type:
  lvm:
    is_public: true

cinder::config::cinder_config:
  lvm/volume_group:
    value: 'cinder-volumes'
