---
#profile::application::builder::insecure:  true
#profile::application::builder::network:   'public'
profile::base::common::manage_lvm:        true


profile::monitoring::sensu::agent::plugin_gems:
  sensu-plugins-himlar:
    ensure:   '0.4.0'
    provider: 'sensuclassic_gem'
    source:   'http://download.iaas.uio.no/uh-iaas/gem'
